#####################################################################
# Make a copy of this file called config_local.yaml and place
# it at the root level of the repository
#
# This file holds local settings specific to your computing
# environment. It should not be committed to the repository.
#####################################################################

#####################################################################
# External dependencies
#
# This section defines resources used by the code that are external
# to the repository. Code should never reference any files external 
# to the repository except via these paths.
#
# Each external resource is defined by a key with a value equal
# to the local path to the resource. These
# keys should be short descriptive names that will then be used
# to refer to these resources in code. E.g., "raw_data", 
# "my_other_repo", etc. Defaults can optionally be placed in
# brackets after the colon
#
# Replace the paths below with correct local paths on your machine
#
#####################################################################
external:
  big_dataset: path_to_big_dataset
  good_code_library: path_to_good_code_library

#####################################################################
# Local settings
#
# This section defines parameters specific to each user's local 
# environment. 
#
# Examples include names of executables, usernames, etc. These
# variables should NOT be used to store passwords.
#
# Each parameter is defined by a key with default value. These
# keys should be short descriptive names that will then be used
# to refer to the parameters in code.
#
#####################################################################
local:

  # Executable names
  executables:
    python: python
    r: Rscript
    stata: stata-mp
    matlab: matlab
    lyx: lyx
    latex: latex

